services:
  app-dev:
    image: seanzie/our-family-hub-dev:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/our-family-hub/src
      - ./public:/our-family-hub/public
    ports: 
      - 3000:3000
    environment:
      - AUTH_SECRET=${AUTH_SECRET_DEV}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID_DEV}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET_DEV}
      - DEV=true
      - DATABASE_PORT=${POSTGRES_PORT_DEV}
      - DATABASE_HOST=${POSTGRES_HOST_DEV}
      - DATABASE_NAME=${POSTGRES_DB_DEV}
      - DATABASE_USER=${POSTGRES_USER_DEV}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD_DEV}
    depends_on:
      - database-dev

  database-dev:
    image: postgres
    environment: 
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - POSTGRES_DB=${POSTGRES_DB_DEV}
    volumes: 
      - db_data_dev:/var/lib/postgresql/data
      - ./db-init/01.init-db.sql:/docker-entrypoint-initdb.d/01.init-db.sql
      - ./db-init/02.dev.populate-db.sql:/docker-entrypoint-initdb.d/02.dev.populate-db.sql

volumes:
  db_data_dev:
