services:
  app:
    image: seanzie/our-family-hub:latest
    build:
      context: .
    ports: 
      - 3000:3000
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_HOST=${POSTGRES_HOST}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database

  database:
    image: postgres
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./db-init/01.init-db.sql:/docker-entrypoint-initdb.d/01.init-db.sql

volumes:
  db_data:
