services:
  app:
    image: seanzie/our-family-hub:latest
    build:
      context: .
    ports: 
      - 3000:3000
    environment:
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_HOST=${POSTGRES_HOST}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    depends_on:
      - database
    restart: on-failure:3

  database:
    image: postgres
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./db-init/01.init-db.sql:/docker-entrypoint-initdb.d/01.init-db.sql
    restart: on-failure:3

volumes:
  db_data:
